export const filmFeed = [
  {
    Id: "ST00000032",
    Title: "Passengers",
    ShortName: "Passengers",
    Synopsis:
      "On a routine journey through space to a new home, two passengers, sleeping in suspended animation, are awakened 90 years too early when their ship malfunctions.",
    Genre: "Romance, Mystery",
    SignageText: "Passengers",
    Distributor: "20th Century Fox",
    OpeningDate: "2016-10-08T00:00:00",
    Rating: "12A",
    Status: "Active",
    Content: "Restricted to persons 13 years and over",
    Duration: 116,
    NationalCode: null,
    Format: "3D Digital",
    IsRestricted: false,
    People: [
      {
        Id: "0000000032",
        FirstName: "Chris",
        LastName: "Pratt",
        Role: "Actor",
      },
      {
        Id: "HO00000176",
        FirstName: "Morten",
        LastName: "Tyldum",
        Role: "Director",
      },
      {
        Id: "HO00000578",
        FirstName: "Jennifer",
        LastName: "Lawrence",
        Role: "Actor",
      },
    ],
    AudioLanguage: "English",
    GovernmentFilmTitle: "Passengers",
    FilmPosterUrl:
      "http://s3.foxmovies.com/foxmovies/production/films/18/images/posters/251-asset-page.jpg",
    FilmPosterThumbnailUrl:
      "https://ticketing.test.veezi.com/Media/Poster?siteToken=u7DHr7RbOk62MQa4x8iK9Q==&code=0000000100",
    BackdropImageUrl:
      "https://ticketing.test.veezi.com/Media/Poster?siteToken=u7DHr7RbOk62MQa4x8iK9Q==&code=0000000100",
    FilmTrailerUrl: "https://www.youtube.com/watch?v=5PSNL1qE6VY",
  },
  {
    Id: "ST00000033",
    Title: "Captain Marvel",
    ShortName: "Captain Marvel",
    Synopsis:
      "Captain Marvel is an extraterrestrial Kree warrior who finds herself caught in the middle of an intergalactic battle between her people and the Skrulls.",
    Genre: "Action, Sci-Fi",
    SignageText: "Passengers",
    Distributor: "20th Century Fox",
    OpeningDate: "2018-07-08T00:00:00",
    Rating: "12A",
    Status: "Active",
    Content: "Restricted to persons 13 years and over",
    Duration: 123,
    NationalCode: null,
    Format: "3D Digital",
    IsRestricted: false,
    People: [
      {
        Id: "0000000032",
        FirstName: "Brie",
        LastName: "Larson",
        Role: "Actor",
      },
      {
        Id: "HO00000176",
        FirstName: "Anna",
        LastName: "Boden",
        Role: "Director",
      },
      {
        Id: "HO00000176",
        FirstName: "Ryan",
        LastName: "Fleck",
        Role: "Director",
      },
      {
        Id: "HO00000578",
        FirstName: "Jude",
        LastName: "Law",
        Role: "Actor",
      },
    ],
    AudioLanguage: "English",
    GovernmentFilmTitle: "Passengers",
    FilmPosterUrl:
      "http://s3.foxmovies.com/foxmovies/production/films/18/images/posters/251-asset-page.jpg",
    FilmPosterThumbnailUrl:
      "https://ticketing.test.veezi.com/Media/Poster?siteToken=u7DHr7RbOk62MQa4x8iK9Q==&code=0000000100",
    BackdropImageUrl:
      "https://ticketing.test.veezi.com/Media/Poster?siteToken=u7DHr7RbOk62MQa4x8iK9Q==&code=0000000100",
    FilmTrailerUrl: "https://www.youtube.com/watch?v=5PSNL1qE6VY",
  },
];

export const showFeed = [
  {
    Id: 702,
    FilmId: "ST00000032",
    FilmPackageId: null,
    Title: "Passengers",
    ScreenId: 2,
    Seating: "Select",
    AreComplimentariesAllowed: true,
    ShowType: "Public",
    SalesVia: ["WWW", "POS"],
    Status: "Open",
    PreShowStartTime: "2021-01-22T13:00:00",
    SalesCutOffTime: "2021-01-22T16:50:00",
    FeatureStartTime: "2021-01-20T17:00:00",
    FeatureEndTime: "2021-01-20T18:49:00",
    CleanupEndTime: "2021-01-20T18:49:00",
    TicketsSoldOut: true,
    FewTicketsLeft: false,
    SeatsAvailable: 70,
    SeatsHeld: 0,
    SeatsHouse: 3,
    SeatsSold: 2,
    FilmFormat: "2D Digital",
    PriceCardName: "General Admission",
  },
  {
    Id: 703,
    FilmId: "ST00000032",
    FilmPackageId: null,
    Title: "Passengers",
    ScreenId: 2,
    Seating: "Select",
    AreComplimentariesAllowed: true,
    ShowType: "Public",
    SalesVia: ["WWW", "POS"],
    Status: "Open",
    PreShowStartTime: "2021-01-22T19:00:00",
    SalesCutOffTime: "2021-01-20T16:50:00",
    FeatureStartTime: "2021-01-20T17:00:00",
    FeatureEndTime: "2021-01-20T18:49:00",
    CleanupEndTime: "2021-01-20T18:49:00",
    TicketsSoldOut: true,
    FewTicketsLeft: false,
    SeatsAvailable: 70,
    SeatsHeld: 0,
    SeatsHouse: 3,
    SeatsSold: 2,
    FilmFormat: "2D Digital",
    PriceCardName: "General Admission",
  },
  {
    Id: 704,
    FilmId: "ST00000032",
    FilmPackageId: null,
    Title: "Passengers",
    ScreenId: 2,
    Seating: "Select",
    AreComplimentariesAllowed: true,
    ShowType: "Public",
    SalesVia: ["WWW", "POS"],
    Status: "Open",
    PreShowStartTime: "2021-01-21T17:00:00",
    SalesCutOffTime: "2021-01-21T16:50:00",
    FeatureStartTime: "2021-01-22T17:00:00",
    FeatureEndTime: "2021-01-21T18:49:00",
    CleanupEndTime: "2021-01-21T18:49:00",
    TicketsSoldOut: true,
    FewTicketsLeft: false,
    SeatsAvailable: 70,
    SeatsHeld: 0,
    SeatsHouse: 3,
    SeatsSold: 2,
    FilmFormat: "2D Digital",
    PriceCardName: "General Admission",
  },
  {
    Id: 801,
    FilmId: "ST00000033",
    FilmPackageId: null,
    Title: "Captain Marvel",
    ScreenId: 2,
    Seating: "Select",
    AreComplimentariesAllowed: true,
    ShowType: "Public",
    SalesVia: ["WWW", "POS"],
    Status: "Open",
    PreShowStartTime: "2021-01-21T17:00:00",
    SalesCutOffTime: "2021-01-21T16:50:00",
    FeatureStartTime: "2021-01-22T17:00:00",
    FeatureEndTime: "2021-01-21T18:49:00",
    CleanupEndTime: "2021-01-21T18:49:00",
    TicketsSoldOut: true,
    FewTicketsLeft: false,
    SeatsAvailable: 170,
    SeatsHeld: 0,
    SeatsHouse: 3,
    SeatsSold: 2,
    FilmFormat: "2D Digital",
    PriceCardName: "General Admission",
  },
];
